# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-29 22:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.TextField()),
                ('lastname', models.TextField()),
                ('credit', models.IntegerField()),
                ('queue', models.IntegerField()),
                ('trial', models.BooleanField()),
                ('mobile', models.TextField()),
                ('businessName', models.TextField()),
                ('businessAddress', models.TextField()),
                ('timezone', models.TextField()),
                ('street1', models.TextField()),
                ('street2', models.TextField()),
                ('town', models.TextField()),
                ('zipCode', models.IntegerField()),
                ('country', models.TextField()),
            ],
            options={
                'db_table': 'customers',
            },
        ),
    ]
