# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-29 22:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wowsms', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customer',
            options={'ordering': ['firstname', 'lastname']},
        ),
        migrations.AlterField(
            model_name='customer',
            name='credit',
            field=models.FloatField(),
        ),
    ]
